DROP TABLE IF EXISTS `CUSTOM_FIELDS`;
CREATE TABLE `CUSTOM_FIELDS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DB` varchar(256) DEFAULT NULL,
  `ORIGINAL_TABLE` varchar(256) DEFAULT NULL,
  `SUITECRM_SOURCE_TABLE_NAME` varchar(256) DEFAULT NULL,
  `SUITECRM_SOURCE_COLUMN_NAME` varchar(256) DEFAULT NULL,
  `TYPE_NAME` varchar(256) DEFAULT NULL,
  `COLUMN_SIZE` int(11) DEFAULT NULL,
  `DECIMAL_DIGITS` int(11) DEFAULT NULL,
  `NUM_PREC_RADIX` int(11) DEFAULT NULL,
  `NULLABLE` int(11) DEFAULT NULL,
  `IS_NULLABLE` varchar(256) DEFAULT NULL,
  `IS_AUTOINCREMENT` varchar(256) DEFAULT NULL,
  `FIELD_ENABLED` int(11) DEFAULT 0,
  `TARGET_TABLE` varchar(256) DEFAULT NULL,
  `HAS_LENGTH` char(1) DEFAULT NULL,
  `TARGET_FIELD_NAME` varchar(256) DEFAULT NULL,
  `TARGET_TABLE_ID` varchar(256) DEFAULT NULL,
  `FIELD_CREATED` int(11) DEFAULT 0,
  PRIMARY KEY (`ID`)
);
CREATE INDEX `IDX_CUSTOM_FIELDS_LKP` ON `CUSTOM_FIELDS`(`ID`);
